[project]
name = "ticket_workflow"
version = "0.1.0"
requires-python = ">=3.13,<3.14"

dependencies = [
    "aws-opentelemetry-distro",
    "opentelemetry-instrumentation-langchain >= 0.59.0",
    "langgraph >= 1.0.2",
    "langchain >= 1.0.3",
    "langchain-aws >= 1.0.0",
    "bedrock-agentcore >= 1.8.0",
    "pydantic >= 2.7.0",
    "PyYAML >= 6.0.0",
]